#!/bin/bash

# -- max_steps

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 32 --lora_alpha 64 --lora_dropout 0.05 --lora_bias none --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero2_finetune.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version v1 \
    --data_path /home/baduc/MoVE-KD/playground/data/radimagenet/radimagenet/radimagenet_llava_instruct_balanced_10k_singleturn_formatfix.json \
    --image_folder /home/baduc/MoVE-KD/playground/data/radimagenet/radimagenet \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter ./checkpoints/pretrain/move-kd-biomed7b-v1.1/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/finetune/move-kd-biomedclip-750  \
    --max_steps 750 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to tensorboard \
    --finetune True \
    --tune_encoder True \
    --tune_all False \
    --moe_encoder True \
    --moe_encoder_dense False \
    --moe_encoder_lora_rank 32 \
    --moe_encoder_lora_alpha 1 \
    --moe_encoder_num_experts 3 \
    --moe_encoder_balance_w 0.01 \
    --kd True \
    --kd_w 0.5 \
    --kd_memory_w 0.8 \
    --pretrain_mole_encoder ./checkpoints/pretrain/move-kd-biomed7b-v1.1/mole_encoder.bin \
    --pretrain_encoder_adapter ./checkpoints/pretrain/move-kd-biomed7b-v1.1/encoder_adapter.bin \
    --tune_encoder_adapter True \
    --encoder_teachers clip biomed_clip \
    --token_weight True \
    --teacher_weight True
